INSERT INTO reply (content, post_id, pub_id) VALUES
    ('Have no idea but maybe you could try delete the whole repo and git clone it again. The first time I ran download.sh it just says ERROR 403: Forbidden. like the last line of your error message, after I delete the whole repo and git clone it again it works quite well.', 1, 12),
    ('Tried but doesn''t work. does it mean we can''t download the model in China ?', 1, 1),
    ('Don''t think so. I deployed it on remote server in my school and there wasn''t VPN or proxy or something like that on the device, but it worked.', 1, 12),
    ('Could you try directly running the command without the " --llama_version 2" as that may not be a valid argument', 2, 5),
    ('Thank you for sharing your input. However, there is no difference in the output. I had given this parameter after checking the source code in convert_llama_weights_to_hf.py. The reason of providing this parameter was: "I thought that by giving the model version the script may work and the JSON error may go away"', 2, 2),
    ('I am not able to reproduce the issue on my side. Could you please provide the exact steps you followed and the entire stack trace? Thanks!', 2, 5),
    ('I had followed the exact steps listed here https://ai.meta.com/blog/5-steps-to-getting-started-with-llama-2/', 2, 2),
    ('Thank you. Could you check if the params.json file is in the same directory as the model you are trying to convert, and that it''s called exactly params.json? Also, could you double check if the json is a valid json file and not malformed?', 2, 5),
    ('The difference observed in the pretraining loss curves between LLaMA and LLaMA2 could be due to various factors: Improved Training Techniques: LLaMA2 might have benefited from advancements or refinements in training techniques compared to LLaMA. These improvements could lead to smoother loss curves and more stable training. Different Architectures or Hyperparameters: LLaMA2 may have used different model architectures or hyperparameters compared to LLaMA, resulting in smoother convergence during training. Data Variability: The datasets used for pretraining LLaMA and LLaMA2 might have had different characteristics or levels of noise. A more varied or noisy dataset could result in a loss curve with more fluctuations. Data Processing or Augmentation: Differences in data preprocessing or augmentation techniques between LLaMA and LLaMA2 could also influence the smoothness of the loss curves. Graphical Representation: It''s also possible that the smoothing applied to the visualization of the loss curve in LLaMA2 might differ from that of LLaMA, leading to the appearance of a smoother curve.', 3, 1),
    ('Moving this to meta-llama/llama as this touched the original paper.', 3, 10),
    ('Hello, I have encountered the same problem. I have been sending the request for a week now. Have you received a reply?', 4, 3),
    ('Hi, yeap I downloaded it from unofficial link that I found on another ones repo. I think it is not appropriate to share the link here but you can find it if you google it more.', 4, 14),
    ('Hi @mntalha I tried downloading today using this link https://llama.meta.com/llama-downloads/ then I instantly got the mail on how to move forward with its download !', 5, 1),
    ('Hi, Interesting, which models did you choose to access? I chose all in my application.', 5, 7),
    ('Hello Same even I chose all the models !', 5, 1),
    ('Please try again and let us know if it doesn''t work. We are trying to streamline the approval process so it should be a lot faster.', 5, 16),
    ('Hi! I am able to download the llama2 models directly via the email/meta release form, but have not gotten HF approval. The emails I used are the same (zche@umd.edu). The HF repo I''m requesting access to is Llama-2-7b-chat-hf. I can''t resubmit a HF access request. It''s been a while (~a month?) since my HF request. Could you help me troubleshoot this?', 5, 16),
    ('Thank you, I received an email by Meta and installed the model successfully.', 5, 7),
    ('any answer? I meet the same question.', 6, 12),
    ('I think you can overwirte model to get the hidden state.', 6, 3),
    ('Have you implemented it? Would you mind sharing the code?', 6, 12),
    ('I lost my code. I can share my thought to you. During debugging, you can identify one hidden state to map to a vocabulary size of 32000. That should be the hidden state of the last layer of Llama2.', 6, 3),
    ('Thanks for your kind reply~', 6, 12),
    ('Good', 7, 1),
    ('Do you need assistance?', 7, 13),
    ('I love to be your assistance', 7, 5),
    ('It doesn''t appear this went update was made, but I would say Parasite would also fall under this header.', 8, 2),
    ('Java is a widely used object-oriented programming language and software platform that runs on billions of devices, including notebook computers, mobile devices, gaming consoles, medical devices and many others. The rules and syntax of Java are based on the C and C++ languages.', 8, 17),
    ('better u add parasite under header', 8, 12),
    ('Replace the text in all the images ?', 9, 11),
    ('Is ''Dominant'' and ''Submissive'' allowed? ', 9, 6),
    ('I''d like to work on this issue, can you explain me where the link is broken, that is in either documentation or somewhere else.', 10, 1),
    ('The link is in the No SQL section. Is the one labeled as ''redis architecture''', 10, 7),
    ('Can you assign this issue to me, and share the link for redis architecture', 10, 9),
    ('/assign', 11, 11),
    ('important-longterm', 11, 12),
    ('I looks like the analogous situation is inside manageJob, for example when suspending a job here, we update the active count, but not terminating, so the terminating counter is lagging behind as the events propagate.', 11, 5),
    ('This issue is currently awaiting triage.  If a SIG or subproject determines this is a relevant issue, they will accept it by applying the triage/accepted label and provide further guidance.  The triage/accepted label can be added by org members by writing /triage accepted in a comment.', 12, 14),
    ('as a workaround, can you combine the two volumes and use subpath for different mounts? Does localcsi driver support storage capacity tracking? If it relies on that feature, enhancement is still needed as it currently only supports one PVC per Pod.', 12, 8),
    ('Thank you for your reply. I''ll think about this solution.', 12, 1),
    ('errors.As will panic if target is not a non-nil pointer to either a type that implements error, or to any interface type. As returns false if err is nil. But syscall.Errno clearly implements error.', 13, 15),
    ('According to the changelog, kubernentes v1.28.6 (what I''m using) is built with go 1.21.7', 13, 5),
    ('do you have a more succinct reproducer to make it easier to find the issue?', 13, 4),
    ('Not really sorry. The only weird thing which may be relevant: This happened on a control plane node, and I didn''t have any taints on my control plane nodes, so it was running normal pods as well as control plane pods. No idea if that''s relevant.', 13, 1),
    ('windows', 14, 1),
    ('Try this way kubectl.exe cp --kubeconfig .\kubconfig -n namespace-win pod-20240509-120334-779546rrfsc:C:/data/0509-1065.log ./0509-1065.log', 14, 1),
    ('It failed. It shows', 14, 2),
    ('maybe it should be a different issue, but this is redundant too:', 15, 1),
    ('I believe @gfavor is aware that one of the many, many things on his to-do list is to better integrate the Sstc chapter. (Sstc is certainly not the only offender in this regard.)', 15, 5),
    ('the architecture), and PMAs are managed by M-mode firmware, it is up to that implementation-specific firmware to do any necessary sfence''ing when PMAs are changed.  This is true for all memory accesses, not just PTE memory accesses.', 16, 7),
    ('Configurable PMAs are custom and implementation defined, not defined by the spec, so I suspect there is a "correct" answer.', 16, 9),
    ('OK, got it. Thanks a lot.', 16, 15),
    ('My understanding is that mtvec can be hardwired to one specific value if you want (e.g. the handler is in ROM). So it doesn''t need to support all invalid addresses or even all valid addresses. The others need to support all valid addresses.', 17, 3),
    ('No, the constraints on mepc and mtval are inherently a little different from mtvec. Indeed it''s not useful for mtvec to be able to hold invalid addresses. But it is important that mepc and mtval hold at least one invalid address, to indicate the reason for an exception is that the address is invalid (as opposed to being valid but currently faulting).', 17, 16),
    ('ok - thanks - so the rationale is that mtvec doesn''t need to be able to hold any invalid addresses whereas mepc and the others must store at least one.', 17, 1),
    ('A fine summary of the discussion.', 17, 12),
    ('Ping for comments.', 18, 14),
    ('No, there is no plan to add such a feature.', 18, 1),
    ('If so, then there is no meaning for getcpu in vDSO, which may cause some performance issues compared to other archs. What if we add an extension to expose mhartid to unprivileged code?', 18, 14),
    ('There is a reason to have getcpu in the vDSO, which is that a user-space facility could eventually be added if deemed necessary. Perhaps its day will come.', 18, 1),
    ('I agree with you. Tianren Li is a bad guy and we should not trust him or accept his papers.', 19, 1),
    ('I think what this post says is not true. I have been working with Tianren Li for a long time and I think he is a good guy.', 19, 5),
    ('I think this post is not appropriate. We should not talk about personal issues here.', 19, 7),
    ('I agree with you. We should not talk about personal issues here.', 19, 16),
    ('Hello, I have encountered the same problem. I have been sending the request for a week now. Have you received a reply?', 20, 3),
    ('Hi, yeap I downloaded it from unofficial link that I found on another ones repo. I think it is not appropriate to share the link here but you can find it if you google it more.', 20, 14),
    ('Hi @mntalha I tried downloading today using this link https://llama.meta.com/llama-downloads/ then I instantly got the mail on how to move forward with its download !', 21, 1),
    ('Hi, Interesting, which models did you choose to access? I chose all in my application.', 21, 7),
    ('Hello Same even I chose all the models !', 21, 1),
    ('Please try again and let us know if it doesn''t work. We are trying to streamline the approval process so it should be a lot faster.', 21, 16),
    ('Hi! I am able to download the llama2 models directly via the email/meta release form, but have not gotten HF approval. The emails I used are the same (zche@umd.edu). The HF repo I''m requesting access to is Llama-2-7b-chat-hf. I can''t resubmit a HF access request. It''s been a while (~a month?) since my HF request. Could you help me troubleshoot this?', 21, 16),
    ('Thank you, I received an email by Meta and installed the model successfully.', 21, 7),
    ('any answer? I meet the same question.', 22, 12),
    ('I think you can overwirte model to get the hidden state.', 22, 3),
    ('Have you implemented it? Would you mind sharing the code?', 22, 12),
    ('I lost my code. I can share my thought to you. During debugging, you can identify one hidden state to map to a vocabulary size of 32000. That should be the hidden state of the last layer of Llama2.', 22, 3),
    ('Thanks for your kind reply~', 22, 12);
